#! /bin/bash

dest=configs/$1

if [[ ! -e $dest ]] 
then
  echo "CREATING $dest"
  mkdir -p $dest/chatLogs
  echo "... copying text files"
  cp config_default/*.cfg $dest
  cp config_default/game_text.json $dest

  echo "... creating gameDB"
  sqlite3 $dest/gameDB.db  < config_default/gameDB.sql
  echo "... creating mapDB"
  sqlite3 $dest/mapDB.db   < config_default/mapDB.sql
  echo "... creating usersDB"
  sqlite3 $dest/usersDB.db < config_default/usersDB.sql
  echo "DONE"
else
  echo "ERROR - Already exists: $dest"
  exit 1
fi
